package telegramui

import "fmt"

// GlobalSurfaceID is a reserved logical identity for owner-only menus which
// are not tied to a provider session. Provider session UUIDs are versioned
// random UUIDs, so this reserved all-zero namespace cannot be generated by the
// application lifecycle.
const GlobalSurfaceID = "00000000-0000-0000-0000-000000000001"

// Action identifies a copy-independent Telegram card action.
type Action string

const (
	ActionPagePrevious                         Action = "page_previous"
	ActionPageLatest                           Action = "page_latest"
	ActionPageNext                             Action = "page_next"
	ActionStop                                 Action = "stop"
	ActionClose                                Action = "close"
	ActionOptions                              Action = "options"
	ActionScreen                               Action = "screen"
	ActionSelectSession                        Action = "select_session"
	ActionResume                               Action = "resume"
	ActionMenuSessions                         Action = "menu_sessions"
	ActionMenuNew                              Action = "menu_new"
	ActionMenuArchive                          Action = "menu_archive"
	ActionMenuStatus                           Action = "menu_status"
	ActionMenuSettings                         Action = "menu_settings"
	ActionMenuBack                             Action = "menu_back"
	ActionCreateCodex                          Action = "create_codex"
	ActionCreateClaude                         Action = "create_claude"
	ActionSettingsScreen                       Action = "settings_screen"
	ActionSettingsDetail                       Action = "settings_detail"
	ActionAuthorizeCodex                       Action = "authorize_codex"
	ActionAuthorizeClaude                      Action = "authorize_claude"
	ActionInteractionChoice                    Action = "interaction_choice"
	ActionInteractionAccept                    Action = "interaction_accept"
	ActionInteractionDecline                   Action = "interaction_decline"
	ActionInteractionCancel                    Action = "interaction_cancel"
	ActionOutboundConfirmDelivered             Action = "outbound_confirm_delivered"
	ActionOutboundRetryPossibleDuplicate       Action = "outbound_retry_possible_duplicate"
	ActionCallbackEffectConfirmed              Action = "callback_effect_confirmed"
	ActionCallbackEffectRetryPossibleDuplicate Action = "callback_effect_retry_possible_duplicate"
	ActionCallbackSendConfirmed                Action = "callback_send_confirmed"
	ActionCallbackSendRetryPossibleDuplicate   Action = "callback_send_retry_possible_duplicate"
	ActionInteractionOther                     Action = "interaction_other"
	ActionAcceptedTurnAssumeCompleted          Action = "accepted_turn_assume_completed"
	ActionAcceptedTurnRetryPossibleDuplicate   Action = "accepted_turn_retry_possible_duplicate"
	ActionAcceptedTurnCancel                   Action = "accepted_turn_cancel"
	ActionStatusRecoveryAssumeDelivered        Action = "status_recovery_assume_delivered"
	ActionStatusRecoveryRetryPossibleDuplicate Action = "status_recovery_retry_possible_duplicate"
	ActionStatusRecoveryCancel                 Action = "status_recovery_cancel"
	ActionArtifactRetry                        Action = "artifact_retry"
)

func IsGlobalAction(action Action) bool {
	switch action {
	case ActionMenuSessions, ActionMenuNew, ActionMenuArchive, ActionMenuStatus,
		ActionMenuSettings, ActionMenuBack, ActionCreateCodex, ActionCreateClaude,
		ActionSettingsScreen, ActionSettingsDetail, ActionAuthorizeCodex, ActionAuthorizeClaude:
		// Outbound resolution is also an owner-only global surface, but its
		// exact operation/update identity is bound server-side by the presenter.
		return true
	case ActionOutboundConfirmDelivered, ActionOutboundRetryPossibleDuplicate:
		return true
	case ActionCallbackEffectConfirmed, ActionCallbackEffectRetryPossibleDuplicate,
		ActionCallbackSendConfirmed, ActionCallbackSendRetryPossibleDuplicate:
		return true
	case ActionStatusRecoveryAssumeDelivered, ActionStatusRecoveryRetryPossibleDuplicate, ActionStatusRecoveryCancel:
		return true
	default:
		return false
	}
}

func IsStatusRecoveryAction(action Action) bool {
	return action == ActionStatusRecoveryAssumeDelivered || action == ActionStatusRecoveryRetryPossibleDuplicate || action == ActionStatusRecoveryCancel
}

func IsCallbackRecoveryAction(action Action) bool {
	switch action {
	case ActionCallbackEffectConfirmed, ActionCallbackEffectRetryPossibleDuplicate,
		ActionCallbackSendConfirmed, ActionCallbackSendRetryPossibleDuplicate:
		return true
	default:
		return false
	}
}

func IsOutboundResolutionAction(action Action) bool {
	return action == ActionOutboundConfirmDelivered || action == ActionOutboundRetryPossibleDuplicate
}

func IsInteractionAction(action Action) bool {
	switch action {
	case ActionInteractionChoice, ActionInteractionAccept, ActionInteractionDecline, ActionInteractionCancel, ActionInteractionOther:
		return true
	default:
		return false
	}
}

func IsAcceptedTurnRecoveryAction(action Action) bool {
	switch action {
	case ActionAcceptedTurnAssumeCompleted, ActionAcceptedTurnRetryPossibleDuplicate, ActionAcceptedTurnCancel:
		return true
	default:
		return false
	}
}

func IsArtifactRetryAction(action Action) bool { return action == ActionArtifactRetry }

// PageView is one user's semantic position within a card history.
type PageView struct {
	Page         int
	Pages        int
	Anchor       string
	FollowLatest bool
}

// ButtonTarget contains only a semantic target. SessionSlot is one-based and
// deliberately does not contain a logical or provider session identifier.
type ButtonTarget struct {
	Page              int
	FollowLatest      bool
	SessionSlot       int
	InteractionChoice int
}

// PageIndicator supplies numeric content for the copy layer's center button.
type PageIndicator struct {
	Current int
	Total   int
}

// Button is a semantic keyboard button without labels, icons, or encoded
// callback data.
type Button struct {
	Action    Action
	Target    ButtonTarget
	Indicator *PageIndicator
}

type ButtonRow []Button

type CardKeyboard struct {
	Rows []ButtonRow
}

// CardKeyboardInput supplies state that affects the specified card rows.
// SessionRowSizes lets a later presentation layer choose row widths without
// importing the historical implementation's fixed per-row limit.
type CardKeyboardInput struct {
	View            PageView
	Working         bool
	OptionsExpanded bool
	Archived        bool
	SessionRowSizes []int
}

// ProjectCardKeyboard returns the required row order and wrap-around page
// targets without choosing transport copy or callback encoding.
func ProjectCardKeyboard(input CardKeyboardInput) (CardKeyboard, error) {
	if err := validatePageView(input.View); err != nil {
		return CardKeyboard{}, err
	}
	for _, size := range input.SessionRowSizes {
		if size < 1 {
			return CardKeyboard{}, fmt.Errorf("session row size must be positive")
		}
	}

	previous := wrappedPage(input.View.Page-1, input.View.Pages)
	next := wrappedPage(input.View.Page+1, input.View.Pages)
	rows := []ButtonRow{{
		{Action: ActionPagePrevious, Target: ButtonTarget{Page: previous}},
		{
			Action:    ActionPageLatest,
			Target:    ButtonTarget{Page: input.View.Pages, FollowLatest: true},
			Indicator: &PageIndicator{Current: input.View.Page, Total: input.View.Pages},
		},
		{Action: ActionPageNext, Target: ButtonTarget{Page: next}},
	}}

	lifecycle := ActionClose
	if input.Archived {
		lifecycle = ActionResume
	} else if input.Working {
		lifecycle = ActionStop
	}
	rows = append(rows, ButtonRow{{Action: lifecycle}, {Action: ActionOptions}})
	if input.OptionsExpanded {
		rows = append(rows, ButtonRow{{Action: ActionScreen}})
	}

	slot := 1
	for _, rowSize := range input.SessionRowSizes {
		row := make(ButtonRow, rowSize)
		for index := range row {
			row[index] = Button{
				Action: ActionSelectSession,
				Target: ButtonTarget{SessionSlot: slot},
			}
			slot++
		}
		rows = append(rows, row)
	}
	return CardKeyboard{Rows: rows}, nil
}

func validatePageView(view PageView) error {
	if view.Page < 1 || view.Pages < 1 || view.Page > view.Pages {
		return fmt.Errorf("page view must contain a current positive page within its positive total")
	}
	return nil
}

func wrappedPage(page, pages int) int {
	if page < 1 {
		return pages
	}
	if page > pages {
		return 1
	}
	return page
}
