package telegramui

import "fmt"

// GlobalSurfaceID is a reserved logical identity for owner-only menus which
// are not tied to a provider session. Provider session UUIDs are versioned
// random UUIDs, so this reserved all-zero namespace cannot be generated by the
// application lifecycle.
const GlobalSurfaceID = "00000000-0000-0000-0000-000000000001"

// Action identifies a copy-independent Telegram card action.
type Action string

// IsModelSelectorAction identifies session-bound model and effort picker controls.
func IsModelSelectorAction(action Action) bool {
	return action == ActionModelMenu || action == ActionModelChoice || action == ActionEffortMenu || action == ActionEffortChoice
}

// IsSessionSurfaceAction identifies controls bound to a session on a shared surface.
func IsSessionSurfaceAction(action Action) bool {
	return IsModelSelectorAction(action) || action == ActionNativeKey
}

const (
	ActionModelMenu                            Action = "model_menu"
	ActionNativeKey                            Action = "native_key"
	ActionModelChoice                          Action = "model_choice"
	ActionEffortMenu                           Action = "effort_menu"
	ActionEffortChoice                         Action = "effort_choice"
	ActionPagePrevious                         Action = "page_previous"
	ActionPageLatest                           Action = "page_latest"
	ActionPageNext                             Action = "page_next"
	ActionStop                                 Action = "stop"
	ActionClose                                Action = "close"
	ActionOptions                              Action = "options"
	ActionScreen                               Action = "screen"
	ActionSelectSession                        Action = "select_session"
	ActionResume                               Action = "resume"
	ActionMenuSessions                         Action = "menu_sessions"
	ActionMenuNew                              Action = "menu_new"
	ActionMenuArchive                          Action = "menu_archive"
	ActionMenuStatus                           Action = "menu_status"
	ActionRefreshStatus                        Action = "refresh_status"
	ActionMenuSettings                         Action = "menu_settings"
	ActionMenuBack                             Action = "menu_back"
	ActionMenuNodes                            Action = "menu_nodes"
	ActionSelectNode                           Action = "select_node"
	ActionCreateSelectCodex                    Action = "create_select_codex"
	ActionCreateSelectClaude                   Action = "create_select_claude"
	ActionCreateWorkdir                        Action = "create_workdir"
	ActionCreateConfirm                        Action = "create_confirm"
	ActionCreateChoice                         Action = "create_choice"
	ActionCreatePrevious                       Action = "create_previous"
	ActionCreateFirst                          Action = "create_first"
	ActionCreateNext                           Action = "create_next"
	ActionCreateUp                             Action = "create_up"
	ActionCreatePick                           Action = "create_pick"
	ActionCreateDirectoryNew                   Action = "create_directory_new"
	ActionCreateBack                           Action = "create_back"
	ActionCreateFresh                          Action = "create_fresh"
	ActionCreateCodex                          Action = "create_codex"
	ActionCreateClaude                         Action = "create_claude"
	ActionSettingsCategory                     Action = "settings_category"
	ActionSettingsScreen                       Action = "settings_screen"
	ActionSettingsScreenCaptureLimit           Action = "settings_screen_capture_limit"
	ActionSettingsScreenImageProfile           Action = "settings_screen_image_profile"
	ActionSettingsAutoApproveCommands          Action = "settings_auto_approve_commands"
	ActionSettingsDetail                       Action = "settings_detail"
	ActionSettingsPageLimit                    Action = "settings_page_limit"
	ActionSettingsContinueExisting             Action = "settings_continue_existing"
	ActionSettingsTechnicalActions             Action = "settings_technical_actions"
	ActionSettingsTechnicalOutputLines         Action = "settings_technical_output_lines"
	ActionSettingsTechnicalCommandLines        Action = "settings_technical_command_lines"
	ActionSettingsHiddenDirectories            Action = "settings_hidden_directories"
	ActionSettingsBackgroundQuestions          Action = "settings_background_questions"
	ActionSettingsBackgroundErrors             Action = "settings_background_errors"
	ActionSettingsArchiveRecommendations       Action = "settings_archive_recommendations"
	ActionSettingsDefaultProvider              Action = "settings_default_provider"
	ActionSettingsDefaultWorkdir               Action = "settings_default_workdir"
	ActionSettingsClearCreationDefaults        Action = "settings_clear_creation_defaults"
	ActionSettingsLifetimeNever                Action = "settings_lifetime_never"
	ActionSettingsLifetime6Hours               Action = "settings_lifetime_6h"
	ActionSettingsLifetime12Hours              Action = "settings_lifetime_12h"
	ActionSettingsLifetime24Hours              Action = "settings_lifetime_24h"
	ActionSettingsLifetime48Hours              Action = "settings_lifetime_48h"
	ActionSettingsProviderCodex                Action = "settings_provider_codex"
	ActionSettingsProviderClaude               Action = "settings_provider_claude"
	ActionSettingsPreprocessing                Action = "settings_preprocessing"
	ActionSettingsPreprocessingDisabled        Action = "settings_preprocessing_disabled"
	ActionSettingsPreprocessingShared          Action = "settings_preprocessing_shared"
	ActionSettingsPreprocessingPerSession      Action = "settings_preprocessing_per_session"
	ActionSettingsPreprocessingInstruction     Action = "settings_preprocessing_instruction"
	ActionSettingsPreprocessingReset           Action = "settings_preprocessing_reset"
	ActionSettingsSessionNaming                Action = "settings_session_naming"
	ActionSettingsStandby                      Action = "settings_standby"
	ActionSettingsRenameNode                   Action = "settings_rename_node"
	ActionAuthorizeCodex                       Action = "authorize_codex"
	ActionAuthorizeClaude                      Action = "authorize_claude"
	ActionInteractionChoice                    Action = "interaction_choice"
	ActionInteractionAccept                    Action = "interaction_accept"
	ActionInteractionDecline                   Action = "interaction_decline"
	ActionInteractionCancel                    Action = "interaction_cancel"
	ActionOutboundConfirmDelivered             Action = "outbound_confirm_delivered"
	ActionOutboundRetryPossibleDuplicate       Action = "outbound_retry_possible_duplicate"
	ActionCallbackEffectConfirmed              Action = "callback_effect_confirmed"
	ActionCallbackEffectRetryPossibleDuplicate Action = "callback_effect_retry_possible_duplicate"
	ActionCallbackSendConfirmed                Action = "callback_send_confirmed"
	ActionCallbackSendRetryPossibleDuplicate   Action = "callback_send_retry_possible_duplicate"
	ActionInteractionOther                     Action = "interaction_other"
	ActionInteractionPrevious                  Action = "interaction_previous"
	ActionInteractionNext                      Action = "interaction_next"
	ActionInteractionSubmit                    Action = "interaction_submit"
	ActionAcceptedTurnAssumeCompleted          Action = "accepted_turn_assume_completed"
	ActionAcceptedTurnRetryPossibleDuplicate   Action = "accepted_turn_retry_possible_duplicate"
	ActionAcceptedTurnCancel                   Action = "accepted_turn_cancel"
	ActionStatusRecoveryAssumeDelivered        Action = "status_recovery_assume_delivered"
	ActionStatusRecoveryRetryPossibleDuplicate Action = "status_recovery_retry_possible_duplicate"
	ActionStatusRecoveryCancel                 Action = "status_recovery_cancel"
	ActionArtifactRetry                        Action = "artifact_retry"
)

func IsGlobalAction(action Action) bool {
	switch action {
	case ActionMenuSessions, ActionMenuNew, ActionMenuArchive, ActionMenuStatus, ActionRefreshStatus, ActionMenuNodes, ActionSelectNode,
		ActionMenuSettings, ActionMenuBack, ActionCreateSelectCodex, ActionCreateSelectClaude,
		ActionCreateWorkdir, ActionCreateConfirm, ActionCreateCodex, ActionCreateClaude,
		ActionCreateChoice, ActionCreatePrevious, ActionCreateFirst, ActionCreateNext,
		ActionCreateUp, ActionCreatePick, ActionCreateDirectoryNew, ActionCreateBack, ActionCreateFresh,
		ActionSettingsCategory, ActionSettingsScreen, ActionSettingsScreenCaptureLimit, ActionSettingsScreenImageProfile, ActionSettingsAutoApproveCommands, ActionSettingsDetail, ActionSettingsPageLimit, ActionSettingsContinueExisting,
		ActionSettingsTechnicalActions, ActionSettingsTechnicalOutputLines, ActionSettingsTechnicalCommandLines, ActionSettingsBackgroundQuestions, ActionSettingsBackgroundErrors,
		ActionSettingsArchiveRecommendations, ActionSettingsHiddenDirectories,
		ActionSettingsDefaultProvider, ActionSettingsDefaultWorkdir, ActionSettingsClearCreationDefaults,
		ActionSettingsLifetimeNever, ActionSettingsLifetime6Hours, ActionSettingsLifetime12Hours,
		ActionSettingsLifetime24Hours, ActionSettingsLifetime48Hours,
		ActionSettingsProviderCodex, ActionSettingsProviderClaude,
		ActionSettingsPreprocessing, ActionSettingsPreprocessingDisabled, ActionSettingsPreprocessingShared, ActionSettingsPreprocessingPerSession,
		ActionSettingsPreprocessingInstruction, ActionSettingsPreprocessingReset, ActionSettingsSessionNaming, ActionSettingsStandby, ActionSettingsRenameNode,
		ActionAuthorizeCodex, ActionAuthorizeClaude:
		// Outbound resolution is also an owner-only global surface, but its
		// exact operation/update identity is bound server-side by the presenter.
		return true
	case ActionOutboundConfirmDelivered, ActionOutboundRetryPossibleDuplicate:
		return true
	case ActionCallbackEffectConfirmed, ActionCallbackEffectRetryPossibleDuplicate,
		ActionCallbackSendConfirmed, ActionCallbackSendRetryPossibleDuplicate:
		return true
	case ActionStatusRecoveryAssumeDelivered, ActionStatusRecoveryRetryPossibleDuplicate, ActionStatusRecoveryCancel:
		return true
	default:
		return false
	}
}

func IsStatusRecoveryAction(action Action) bool {
	return action == ActionStatusRecoveryAssumeDelivered || action == ActionStatusRecoveryRetryPossibleDuplicate || action == ActionStatusRecoveryCancel
}

func IsCallbackRecoveryAction(action Action) bool {
	switch action {
	case ActionCallbackEffectConfirmed, ActionCallbackEffectRetryPossibleDuplicate,
		ActionCallbackSendConfirmed, ActionCallbackSendRetryPossibleDuplicate:
		return true
	default:
		return false
	}
}

func IsOutboundResolutionAction(action Action) bool {
	return action == ActionOutboundConfirmDelivered || action == ActionOutboundRetryPossibleDuplicate
}

func IsInteractionAction(action Action) bool {
	switch action {
	case ActionInteractionChoice, ActionInteractionAccept, ActionInteractionDecline, ActionInteractionCancel, ActionInteractionOther,
		ActionInteractionPrevious, ActionInteractionNext, ActionInteractionSubmit:
		return true
	default:
		return false
	}
}

func IsAcceptedTurnRecoveryAction(action Action) bool {
	switch action {
	case ActionAcceptedTurnAssumeCompleted, ActionAcceptedTurnRetryPossibleDuplicate, ActionAcceptedTurnCancel:
		return true
	default:
		return false
	}
}

func IsArtifactRetryAction(action Action) bool { return action == ActionArtifactRetry }

// PageView is one user's semantic position within a card history.
type PageView struct {
	Page         int
	Pages        int
	Anchor       string
	FollowLatest bool
}

// ButtonTarget contains only a semantic target. SessionSlot is one-based and
// deliberately does not contain a logical or provider session identifier.
type ButtonTarget struct {
	Page              int
	FollowLatest      bool
	SessionSlot       int
	InteractionChoice int
	Choice            int
}

// PageIndicator supplies numeric content for the copy layer's center button.
type PageIndicator struct {
	Current int
	Total   int
}

// Button is a semantic keyboard button without labels, icons, or encoded
// callback data.
type Button struct {
	Action    Action
	Target    ButtonTarget
	Indicator *PageIndicator
	Label     string
}

type ButtonRow []Button

type CardKeyboard struct {
	Rows []ButtonRow
}

// CardKeyboardInput supplies state that affects the specified card rows.
// SessionRowSizes lets a later presentation layer choose row widths without
// importing the historical implementation's fixed per-row limit.
type CardKeyboardInput struct {
	View               PageView
	Working            bool
	OptionsExpanded    bool
	Archived           bool
	Recovery           bool
	CloseConfirmation  bool
	DeleteConfirmation bool
	SessionRowSizes    []int
	SessionLabels      []string
}

// ProjectCardKeyboard returns the required row order and wrap-around page
// targets without choosing transport copy or callback encoding.
func ProjectCardKeyboard(input CardKeyboardInput) (CardKeyboard, error) {
	if err := validatePageView(input.View); err != nil {
		return CardKeyboard{}, err
	}
	if input.CloseConfirmation {
		if input.Archived || input.Working {
			return CardKeyboard{}, fmt.Errorf("close confirmation requires an idle open session")
		}
		label := "Архивировать"
		if input.DeleteConfirmation {
			label = "Удалить"
		}
		return CardKeyboard{Rows: []ButtonRow{{
			{Action: ActionClose, Target: ButtonTarget{Choice: 1}, Label: label},
			{Action: ActionClose, Target: ButtonTarget{Choice: 2}, Label: "Отмена"},
		}}}, nil
	}
	for _, size := range input.SessionRowSizes {
		if size < 1 {
			return CardKeyboard{}, fmt.Errorf("session row size must be positive")
		}
	}
	selectableCount := 0
	for _, size := range input.SessionRowSizes {
		selectableCount += size
	}
	if len(input.SessionLabels) != 0 && len(input.SessionLabels) != selectableCount {
		return CardKeyboard{}, fmt.Errorf("session labels must match selectable sessions")
	}

	previous := wrappedPage(input.View.Page-1, input.View.Pages)
	next := wrappedPage(input.View.Page+1, input.View.Pages)
	rows := []ButtonRow{{
		{Action: ActionPagePrevious, Target: ButtonTarget{Page: previous}},
		{
			Action:    ActionPageLatest,
			Target:    ButtonTarget{Page: input.View.Pages, FollowLatest: true},
			Indicator: &PageIndicator{Current: input.View.Page, Total: input.View.Pages},
		},
		{Action: ActionPageNext, Target: ButtonTarget{Page: next}},
	}}

	lifecycle := ActionClose
	if input.Archived {
		lifecycle = ActionResume
	} else if input.Working {
		lifecycle = ActionStop
	}
	if input.Recovery {
		rows = append(rows, ButtonRow{{Action: ActionClose}})
	} else {
		rows = append(rows, ButtonRow{{Action: lifecycle}, {Action: ActionOptions}})
	}
	if input.OptionsExpanded && !input.Recovery {
		rows = append(rows, ButtonRow{{Action: ActionScreen}})
	}

	slot := 1
	for _, rowSize := range input.SessionRowSizes {
		row := make(ButtonRow, rowSize)
		for index := range row {
			row[index] = Button{
				Action: ActionSelectSession,
				Target: ButtonTarget{SessionSlot: slot},
			}
			if len(input.SessionLabels) > 0 {
				row[index].Label = input.SessionLabels[slot-1]
			}
			slot++
		}
		rows = append(rows, row)
	}
	rows = append(rows, ButtonRow{
		{Action: ActionMenuNew},
		{Action: ActionMenuNodes},
		{Action: ActionMenuBack},
	})
	return CardKeyboard{Rows: rows}, nil
}

func validatePageView(view PageView) error {
	if view.Page < 1 || view.Pages < 1 || view.Page > view.Pages {
		return fmt.Errorf("page view must contain a current positive page within its positive total")
	}
	return nil
}

func wrappedPage(page, pages int) int {
	if page < 1 {
		return pages
	}
	if page > pages {
		return 1
	}
	return page
}
